/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallsTrackingRouteImport } from './routes/calls/tracking'
import { Route as CallsDumpRouteImport } from './routes/calls/dump'
import { Route as CallsDashboardRouteImport } from './routes/calls/dashboard'

const CallsTrackingRoute = CallsTrackingRouteImport.update({
  id: '/calls/tracking',
  path: '/calls/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsDumpRoute = CallsDumpRouteImport.update({
  id: '/calls/dump',
  path: '/calls/dump',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsDashboardRoute = CallsDashboardRouteImport.update({
  id: '/calls/dashboard',
  path: '/calls/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/calls/dashboard': typeof CallsDashboardRoute
  '/calls/dump': typeof CallsDumpRoute
  '/calls/tracking': typeof CallsTrackingRoute
}
export interface FileRoutesByTo {
  '/calls/dashboard': typeof CallsDashboardRoute
  '/calls/dump': typeof CallsDumpRoute
  '/calls/tracking': typeof CallsTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calls/dashboard': typeof CallsDashboardRoute
  '/calls/dump': typeof CallsDumpRoute
  '/calls/tracking': typeof CallsTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/calls/dashboard' | '/calls/dump' | '/calls/tracking'
  fileRoutesByTo: FileRoutesByTo
  to: '/calls/dashboard' | '/calls/dump' | '/calls/tracking'
  id: '__root__' | '/calls/dashboard' | '/calls/dump' | '/calls/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CallsDashboardRoute: typeof CallsDashboardRoute
  CallsDumpRoute: typeof CallsDumpRoute
  CallsTrackingRoute: typeof CallsTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calls/tracking': {
      id: '/calls/tracking'
      path: '/calls/tracking'
      fullPath: '/calls/tracking'
      preLoaderRoute: typeof CallsTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/dump': {
      id: '/calls/dump'
      path: '/calls/dump'
      fullPath: '/calls/dump'
      preLoaderRoute: typeof CallsDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/dashboard': {
      id: '/calls/dashboard'
      path: '/calls/dashboard'
      fullPath: '/calls/dashboard'
      preLoaderRoute: typeof CallsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CallsDashboardRoute: CallsDashboardRoute,
  CallsDumpRoute: CallsDumpRoute,
  CallsTrackingRoute: CallsTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
